from pydantic import BaseModel, Field
from typing import List, Literal, Optional, Any, Dict

# INPUT MODELS

class RawDiffRequest(BaseModel):
    """
    Schema for the /review-diff endpoint.
    """
    diff_text: str 


class PRWebhookPayload(BaseModel):
    """
    Schema for the GitHub Webhook payload.
    """
    action: str
    number: int
    repository: Dict[str, Any]
    pull_request: Dict[str, Any]

    class Config:
        extra = "ignore"  # ignore extra GitHub fields


# OUTPUT MODELS

class ReviewComment(BaseModel):
    """
    A single atomic review comment generated by an Agent.
    """
    file: str
    line: int
    type: Literal["Security","Quality","Architect"]
    severity: Literal["Critical", "High", "Medium", "Low"]
    message: str
    suggestion: Optional[str] = None


class AnalysisReport(BaseModel):
    """
    The final aggregated object returned by the Orchestrator.
    """
    summary: str 
    comments: List[ReviewComment] = Field(default_factory=list)